from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal
from itertools import pairwise

# Quantiles of the MacKinnon (2010) asymptotic distribution for the residual-based
# cointegration ADF t-statistic: N = 2 variables in the cointegrating regression
# (y plus one regressor), constant included, no trend (``regression="c"``).
#
# Generated by inverting ``statsmodels.tsa.adfvalues.mackinnonp(t, "c", N=2)``; the
# 5% point (-3.33579) reproduces ``mackinnoncrit(N=2, "c", inf)[1] == -3.33613``.
# N counts *variables*, not regressors: ``statsmodels.tsa.stattools.coint`` builds
# ``k_vars = y1.shape[1] + 1`` and passes that as N, so a bivariate pair uses N = 2.
# The table stops at p = 0.99 because ``mackinnonp`` saturates at 1.0 above t ~ 1.0.
_ADF_QUANTILES: tuple[tuple[Decimal, Decimal], ...] = (
    (Decimal("-4.55320"), Decimal("0.001")),
    (Decimal("-4.10841"), Decimal("0.005")),
    (Decimal("-3.89745"), Decimal("0.01")),
    (Decimal("-3.59292"), Decimal("0.025")),
    (Decimal("-3.33579"), Decimal("0.05")),
    (Decimal("-3.04451"), Decimal("0.1")),
    (Decimal("-2.56783"), Decimal("0.25")),
    (Decimal("-2.05480"), Decimal("0.5")),
    (Decimal("-1.52876"), Decimal("0.75")),
    (Decimal("-1.01482"), Decimal("0.9")),
    (Decimal("-0.66782"), Decimal("0.95")),
    (Decimal("-0.31878"), Decimal("0.975")),
    (Decimal("0.22805"), Decimal("0.99")),
)

# MacKinnon (2010) response-surface coefficients for the 1% / 5% / 10% critical
# values, N = 2 and regression = "c", as ``crit(T) = a0 + a1/T + a2/T^2 + a3/T^3``.
# Taken verbatim from ``statsmodels.tsa.adfvalues.tau_2010s["c"][1]``; this module
# reproduces ``mackinnoncrit(N=2, "c", nobs=T)`` exactly for every T we checked.
_ADF_CRIT_COEFFICIENTS: tuple[tuple[Decimal, Decimal, Decimal, Decimal], ...] = (
    (Decimal("-3.89644"), Decimal("-10.9519"), Decimal("-33.527"), Decimal("0")),
    (Decimal("-3.33613"), Decimal("-6.1101"), Decimal("-6.823"), Decimal("0")),
    (Decimal("-3.04445"), Decimal("-4.2412"), Decimal("-2.72"), Decimal("0")),
)
_ADF_ANCHOR_PROBS: tuple[Decimal, ...] = (
    Decimal("0.01"),
    Decimal("0.05"),
    Decimal("0.1"),
)

_MIN_OBSERVATIONS = 30
_MAX_LAGS_CAP = 12
# Minimum observations per estimated parameter; keeps the ADF regression well posed.
_MIN_OBS_PER_PARAM = 5


@dataclass(frozen=True, slots=True)
class CointegrationResult:
    hedge_ratio: Decimal
    intercept: Decimal
    adf_statistic: Decimal
    adf_pvalue: Decimal
    residual_std: Decimal
    adf_lags: int = 0


def fit_cointegration(
    y: tuple[Decimal, ...],
    x: tuple[Decimal, ...],
) -> CointegrationResult:
    """OLS hedge ratio y ~ alpha + beta*x, then an ADF test on the residuals."""
    if len(y) != len(x) or len(y) < _MIN_OBSERVATIONS:
        raise ValueError(f"need at least {_MIN_OBSERVATIONS} aligned observations")
    beta, alpha = _ols_beta_alpha(y, x)
    residuals = tuple(item_y - alpha - beta * item_x for item_y, item_x in zip(y, x, strict=True))
    adf_stat, adf_p, lags = _adf_test(residuals)
    return CointegrationResult(
        hedge_ratio=beta,
        intercept=alpha,
        adf_statistic=adf_stat,
        adf_pvalue=adf_p,
        residual_std=_std(residuals),
        adf_lags=lags,
    )


def _ols_beta_alpha(y: tuple[Decimal, ...], x: tuple[Decimal, ...]) -> tuple[Decimal, Decimal]:
    n = Decimal(len(x))
    mean_x = sum(x, Decimal("0")) / n
    mean_y = sum(y, Decimal("0")) / n
    cov = sum((item_x - mean_x) * (item_y - mean_y) for item_x, item_y in zip(x, y, strict=True))
    var_x = sum((item_x - mean_x) ** 2 for item_x in x)
    if var_x == 0:
        raise ValueError("x has zero variance")
    beta = cov / var_x
    alpha = mean_y - beta * mean_x
    return beta, alpha


def _std(values: tuple[Decimal, ...]) -> Decimal:
    n = Decimal(len(values))
    if n < 2:
        return Decimal("0")
    mean = sum(values, Decimal("0")) / n
    variance = sum((item - mean) ** 2 for item in values) / (n - Decimal("1"))
    return variance.sqrt()


def _adf_test(residuals: tuple[Decimal, ...]) -> tuple[Decimal, Decimal, int]:
    """Augmented Dickey-Fuller t-statistic (no constant) on a residual series.

    The statistic is the **t-ratio** of the ``e_{t-1}`` coefficient in

        dE_t = gamma * E_{t-1} + sum_i delta_i * dE_{t-i} + eps_t

    which is what the MacKinnon tables are tabulated for. The previous
    implementation compared the raw coefficient ``gamma`` instead: since
    ``gamma = rho - 1`` for an AR(1) series and ``rho`` lies in ``(-1, 1)`` for any
    stationary series, ``gamma`` is confined to ``(-2, 0)`` and the hard-coded
    ``gamma < -2.9`` band was unreachable — the gate could never open, so ``pairs``
    could never trade.

    Lag order is chosen by BIC over ``0..p_max`` (Schwert rule) on a **common
    sample** — every candidate lag is fitted on the rows left after trimming
    ``p_max`` lags, so the likelihoods are comparable. Trimming one extra row per
    candidate lag instead would inflate BIC monotonically and always select the
    maximum lag on white-noise residuals, destroying the test's power.

    The winning lag is then re-fitted on its own maximal sample (trimmed by that
    lag alone), which is the statistic that gets reported — the common sample exists
    only to make the BIC comparison fair, and discarding the most recent
    observations from the reported regression would throw away data for no reason.

    ``p`` comes from the MacKinnon quantile table with a finite-sample correction
    for the effective number of observations. Returns ``(t, p, lags)``; a series too
    short to test returns p = 1.
    """
    n = len(residuals)
    if n < _MIN_OBSERVATIONS:
        return Decimal("0"), Decimal("1"), 0

    diffs = tuple(residuals[index + 1] - residuals[index] for index in range(n - 1))
    p_max = _max_lags(n)
    if len(diffs) - p_max <= 1:
        return Decimal("0"), Decimal("1"), 0

    best_lags = 0
    best_bic: Decimal | None = None
    for lags in range(p_max + 1):
        design, response, rows = _adf_design(diffs, residuals, trim=p_max, lags=lags)
        if rows < _MIN_OBS_PER_PARAM * (lags + 1):
            continue
        fit = _ols_first_coefficient(design, response)
        if fit is None:
            continue
        bic = _bic(fit[1], rows, lags + 1)
        if best_bic is None or bic < best_bic:
            best_bic = bic
            best_lags = lags

    design, response, rows = _adf_design(diffs, residuals, trim=best_lags, lags=best_lags)
    fit = _ols_first_coefficient(design, response)
    if fit is None:
        return Decimal("0"), Decimal("1"), best_lags
    t_stat = fit[0]
    return t_stat, p_value_from_statistic(t_stat, rows), best_lags


def _adf_design(
    diffs: tuple[Decimal, ...],
    residuals: tuple[Decimal, ...],
    *,
    trim: int,
    lags: int,
) -> tuple[list[list[Decimal]], list[Decimal], int]:
    """Build the ADF design matrix, dropping ``trim`` leading observations.

    Column 0 is the lagged level ``e_{t-1}``; the rest are the ``lags`` lagged
    differences, so all candidate models share one sample when called with a fixed
    ``trim``.
    """
    indices = range(trim, len(diffs))
    levels = [residuals[index] for index in indices]
    response = [diffs[index] for index in indices]
    columns = [[diffs[index - lag] for index in indices] for lag in range(1, lags + 1)]
    design = [[levels[row], *(column[row] for column in columns)] for row in range(len(response))]
    return design, response, len(response)


def _max_lags(n: int) -> int:
    """Schwert (1989) upper bound floor(12 * (n / 100) ** 0.25), capped and clipped.

    Also clipped so the common sample keeps ``_MIN_OBS_PER_PARAM`` observations per
    estimated parameter even at the largest candidate lag.
    """
    bound = int(12 * (n / 100) ** 0.25)
    feasible = ((n - 1) - _MIN_OBS_PER_PARAM) // (_MIN_OBS_PER_PARAM + 1)
    return max(0, min(bound, _MAX_LAGS_CAP, feasible))


def _bic(rss: Decimal, observations: int, params: int) -> Decimal:
    if rss <= 0:
        return Decimal("Infinity")
    n = Decimal(observations)
    return n * (rss / n).ln() + Decimal(params) * n.ln()


def _ols_first_coefficient(
    design: list[list[Decimal]],
    response: list[Decimal],
) -> tuple[Decimal, Decimal] | None:
    """OLS by normal equations; returns the t-ratio and RSS of the first coefficient.

    Only the first coefficient's standard error is needed, so instead of inverting
    ``X'X`` we solve ``(X'X) z = e_0`` and read ``z[0] = [(X'X)^-1]_00``.
    """
    observations = len(design)
    params = len(design[0])
    dof = observations - params
    if dof <= 0:
        return None

    xtx: list[list[Decimal]] = [
        [sum((row[i] * row[j] for row in design), Decimal("0")) for j in range(params)]
        for i in range(params)
    ]
    xty = [
        sum((row[i] * value for row, value in zip(design, response, strict=True)), Decimal("0"))
        for i in range(params)
    ]

    beta = _solve(xtx, xty)
    if beta is None:
        return None
    unit = [Decimal("1")] + [Decimal("0")] * (params - 1)
    inverse_column = _solve(xtx, unit)
    if inverse_column is None or inverse_column[0] <= 0:
        return None

    rss = Decimal("0")
    for row, value in zip(design, response, strict=True):
        fitted = sum((coef * item for coef, item in zip(beta, row, strict=True)), Decimal("0"))
        residual = value - fitted
        rss += residual * residual

    variance = rss / Decimal(dof)
    standard_error = (variance * inverse_column[0]).sqrt()
    if standard_error == 0:
        return None
    return beta[0] / standard_error, rss


def _solve(matrix: list[list[Decimal]], rhs: list[Decimal]) -> list[Decimal] | None:
    """Gaussian elimination with partial pivoting. Returns None if singular."""
    size = len(matrix)
    augmented = [[*row[:], value] for row, value in zip(matrix, rhs, strict=True)]
    for column in range(size):
        pivot = max(range(column, size), key=lambda row: abs(augmented[row][column]))
        if augmented[pivot][column] == 0:
            return None
        augmented[column], augmented[pivot] = augmented[pivot], augmented[column]
        pivot_value = augmented[column][column]
        for row in range(column + 1, size):
            factor = augmented[row][column] / pivot_value
            if factor == 0:
                continue
            for item in range(column, size + 1):
                augmented[row][item] -= factor * augmented[column][item]

    solution = [Decimal("0")] * size
    for row in range(size - 1, -1, -1):
        total = augmented[row][size] - sum(
            (augmented[row][item] * solution[item] for item in range(row + 1, size)),
            Decimal("0"),
        )
        solution[row] = total / augmented[row][row]
    return solution


def critical_values(nobs: int) -> tuple[Decimal, Decimal, Decimal]:
    """Finite-sample 1% / 5% / 10% critical values for the cointegration t-statistic."""
    return tuple(  # type: ignore[return-value]
        _horner(coefficients, Decimal("1") / Decimal(nobs))
        for coefficients in _ADF_CRIT_COEFFICIENTS
    )


def _horner(coefficients: tuple[Decimal, ...], x: Decimal) -> Decimal:
    total = Decimal("0")
    for coefficient in reversed(coefficients):
        total = total * x + coefficient
    return total


def p_value_from_statistic(t_statistic: Decimal, nobs: int) -> Decimal:
    """Interpolate the ADF p-value, correcting the quantiles for the sample size.

    The stored table is asymptotic. MacKinnon's response surface gives the exact
    critical values at 1%, 5% and 10% for a finite sample; the difference from the
    asymptotic values is interpolated across probability levels and added to the
    whole curve, so the 5% point — the one ``PairsParams.adf_pvalue_max`` gates on
    — is exact, and the rest of the curve is shifted consistently.
    """
    table = _corrected_quantiles(nobs)
    if t_statistic <= table[0][0]:
        return table[0][1]
    if t_statistic >= table[-1][0]:
        return Decimal("0.999")
    for (low_t, low_p), (high_t, high_p) in pairwise(table):
        if low_t <= t_statistic <= high_t:
            fraction = (t_statistic - low_t) / (high_t - low_t)
            return low_p + fraction * (high_p - low_p)
    return Decimal("1")


def _corrected_quantiles(nobs: int) -> tuple[tuple[Decimal, Decimal], ...]:
    deltas = _finite_sample_deltas(nobs)
    return tuple(
        (t_statistic + _interpolate_delta(probability, deltas), probability)
        for t_statistic, probability in _ADF_QUANTILES
    )


def _finite_sample_deltas(nobs: int) -> tuple[tuple[Decimal, Decimal], ...]:
    """Difference between the finite-sample and asymptotic critical values."""
    inverse = Decimal("1") / Decimal(nobs)
    asymptotic = {probability: t_statistic for t_statistic, probability in _ADF_QUANTILES}
    return tuple(
        (probability, _horner(coefficients, inverse) - asymptotic[probability])
        for probability, coefficients in zip(_ADF_ANCHOR_PROBS, _ADF_CRIT_COEFFICIENTS, strict=True)
    )


def _interpolate_delta(
    probability: Decimal,
    deltas: tuple[tuple[Decimal, Decimal], ...],
) -> Decimal:
    if probability <= deltas[0][0]:
        return deltas[0][1]
    if probability >= deltas[-1][0]:
        return deltas[-1][1]
    for (low_p, low_delta), (high_p, high_delta) in pairwise(deltas):
        if low_p <= probability <= high_p:
            fraction = (probability - low_p) / (high_p - low_p)
            return low_delta + fraction * (high_delta - low_delta)
    return Decimal("0")
