// Generated by scripts/gen_api_types.py from src/nautilus_lab/api/responses.py and
// src/nautilus_lab/api/requests.py. Do not edit: change the Pydantic model and run
//   uv run python scripts/gen_api_types.py
// tests/unit/test_api_types.py fails while this file is out of date.

// ---- responses ---------------------------------------------------------------------------

/** How the previous run of a job ended, kept across API restarts (api/job_store.py). */
export interface LastRun {
  status: "running" | "finished" | "lost";
  returncode: number | null;
  finished_at: string | null;
}

export interface JobState {
  running: boolean;
  label: string;
  started_at: string | null;
  elapsed_seconds: number | null;
  /** Started by an earlier API process and taken back after a restart. */
  adopted: boolean;
  last_run: LastRun | null;
}

export interface StressSliceInfo {
  name: string;
  description: string;
  /** ISO-8601 UTC window the slice replaces the load window with. */
  start: string;
  end: string;
}

export interface StatusResponse {
  active_bots: number;
  research_running: boolean;
  ingest_running: boolean;
  ml_running: boolean;
  paper_running: boolean;
  jobs: Record<"research" | "ingest" | "ml_train" | "paper", JobState>;
  strategies_available: string[];
  wired_robots: string[];
  tick_vpin_robots: string[];
  hawkes_robots: string[];
  stress_slices: StressSliceInfo[];
  catalog_exists: boolean;
  catalog_instruments: number;
  catalog_path: string;
  bar_interval: string;
  trading_mode: string;
  /** Robots `lab paper` can actually build. Others are refused, never substituted. */
  paper_robots: string[];
  is_live: boolean;
  live_safe_mode: string;
  /** `paper` = a server that only runs the live paper terminal (LAB_ROLE). */
  lab_role: "full" | "paper";
  live_paper_robots: string[];
  /** True when the live paper ledger is journalled and survives restarts. */
  live_paper_persisted: boolean;
}

export interface HealthResponse {
  status: "ok";
}

/**
 * What a start/stop/cancel button gets back. `status` names the outcome.
 *
 * Every job-launching `POST` answers HTTP 200 with `status: "error"` when another job
 * of the same kind is already running. Callers must check this: ignoring it left the UI
 * spinning while showing the previous run's numbers as if they were new.
 *
 * Sent without the fields a route did not fill (`response_model_exclude_none`), as
 * before the model existed, so they are optional here.
 */
export interface ActionResult {
  status: string;
  message?: string | null;
  command?: string | null;
  disclaimer?: string | null;
}

export interface JobLogResponse {
  is_running: boolean;
  log: string;
}

export interface CatalogSummary {
  path: string;
  exists: boolean;
  total_instruments: number;
  error: string | null;
}

export interface CatalogsResponse {
  default: string;
  catalogs: CatalogSummary[];
}

export interface ReportItem {
  filename: string;
  path: string;
  url: string;
  /** Local time of the file, `YYYY-MM-DD HH:MM:SS`. */
  modified: string;
  size_kb: number;
}

export interface ReportsResponse {
  reports: ReportItem[];
}

export interface MlModelInfo {
  filename: string;
  path: string;
  size_kb: number;
  /** File modification time, seconds since the epoch. */
  modified: number;
}

export interface MlModelsResponse {
  models: MlModelInfo[];
}

export interface CatalogInstrument {
  instrument_id: string;
  raw_symbol: string;
  bars_count: number;
  first_date: string | null;
  last_date: string | null;
  quote_currency: string;
  maker_fee: number;
  taker_fee: number;
}

export interface CatalogResponse {
  catalog_path: string;
  exists: boolean;
  bar_interval: string | null;
  total_instruments: number | null;
  instruments: CatalogInstrument[];
  error: string | null;
}

export interface CatalogBarPoint {
  time: number;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
}

export interface CatalogBarsResponse {
  instrument_id: string;
  bar_type: string;
  bar_interval: string;
  catalog_path: string;
  count: number;
  first_date: string | null;
  last_date: string | null;
  bars: CatalogBarPoint[];
}

export interface StrategyParam {
  env: string;
  name: string | null;
  type: string | null;
  default: unknown;
  description: string | null;
}

export interface StrategySpec {
  name: string;
  title: string | null;
  domain_module: string | null;
  strategy_class: string | null;
  backtest_adapter: string | null;
  wired_in_backtest: boolean;
  minimum_bars: number;
  grid_source: string | null;
  signal_kind: string | null;
  status: string;
  summary: string;
  hypothesis: string | null;
  invariants: Record<string, unknown> | null;
  params: StrategyParam[];
}

export interface StrategiesResponse {
  strategies: StrategySpec[];
  failed_specs: string[];
}

export interface SettingField {
  key: string;
  label: string;
  field_type: "string" | "number" | "boolean" | "select" | "secret";
  description: string;
  options: string[] | null;
}

export interface SettingGroup {
  id: string;
  title: string;
  description: string;
  fields: SettingField[];
}

export interface SettingsSchemaResponse {
  groups: SettingGroup[];
  allowed_keys: string[];
}

export interface SettingsResponse {
  settings: Record<string, string>;
}

// ---- requests ----------------------------------------------------------------------------

export interface ResearchRunRequest {
  robot?: string;
  source?: string;
  bars?: number;
  folds?: number;
  is_fraction?: number;
  embargo_bars?: number | null;
  use_optuna?: boolean;
  optuna_trials?: number;
  pbo?: boolean;
  pbo_blocks?: number;
  bar_vpin?: boolean;
  tick_vpin?: boolean;
  hawkes?: boolean;
  stress_slice?: string | null;
  generate_tearsheet?: boolean;
  journal?: boolean;
  notify?: boolean;
  full_sample?: boolean;
  catalog_path?: string | null;
  instrument_id?: string | null;
  bar_interval?: string | null;
  is_start?: string | null;
  is_end?: string | null;
  oos_start?: string | null;
  oos_end?: string | null;
  param_overrides?: Record<string, string>;
}

export interface IngestRunRequest {
  symbols?: string;
  start?: string | null;
  end?: string | null;
  catalog?: string | null;
  incremental?: boolean;
  series?: string;
}

export interface SettingsUpdate {
  settings: Record<string, string>;
}

export interface MLTrainRequest {
  model_type?: string;
  catalog_path?: string | null;
  instrument_id?: string | null;
  bar_interval?: string | null;
  output_path?: string | null;
  folds?: number;
  embargo?: number;
  horizon?: number;
  profit_multiple?: string;
  stop_multiple?: string;
  vol_window?: number;
  start?: string | null;
  end?: string | null;
  threshold?: string;
}

export interface PaperRunRequest {
  robot?: string;
  bars?: number;
  source?: string;
}

export interface PaperLiveStartRequest {
  symbol?: string;
  interval?: string;
  robot?: string;
  starting_equity?: string;
  risk_per_trade?: string;
  stop_pct?: string;
  take_profit_multiple?: string;
  mode?: string;
  auto_trade?: boolean;
  name?: string;
  notes?: string;
}

export interface PaperLiveStopsUpdateRequest {
  stop_loss?: string | null;
  take_profit?: string | null;
}

export interface JournalPatchRequest {
  decision: string;
}

export interface ProposeRequest {
  count?: number;
  dry_run?: boolean;
  prompt?: string;
  as_of?: string | null;
  model?: string | null;
  base_url?: string | null;
  output_dir?: string | null;
  slug?: string | null;
  journal?: boolean;
}
