"""TypeScript types for the dashboard, generated from the API's Pydantic models.

    uv run python scripts/gen_api_types.py           # write frontend/src/services/api.gen.ts
    uv run python scripts/gen_api_types.py --check   # exit 1 when the file is stale

Why not `openapi-typescript` (docs/27 E-2.3 named it): the models are the single source,
and reading their JSON schema here needs no Node toolchain, no running app and no extra
npm dependency. The drift check then runs in the same `pytest` as everything else
(`tests/unit/test_api_types.py`), so a Python change that alters a response cannot pass
CI with a stale frontend type.

Responses are generated in serialization mode (every field is present in what the API
sends, `null` included); requests in validation mode (fields with defaults are optional
to send). Only the JSON-schema subset these models use is supported; anything else
raises instead of producing a quietly wrong type.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Iterable, Mapping
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel
from pydantic.json_schema import models_json_schema

from nautilus_lab.api import requests, responses

OUTPUT = Path(__file__).resolve().parents[1] / "frontend" / "src" / "services" / "api.gen.ts"

HEADER = """\
// Generated by scripts/gen_api_types.py from src/nautilus_lab/api/responses.py and
// src/nautilus_lab/api/requests.py. Do not edit: change the Pydantic model and run
//   uv run python scripts/gen_api_types.py
// tests/unit/test_api_types.py fails while this file is out of date.
"""

Mode = Literal["serialization", "validation"]


def request_models() -> tuple[type[BaseModel], ...]:
    return tuple(
        value
        for value in vars(requests).values()
        if isinstance(value, type)
        and issubclass(value, BaseModel)
        and value is not BaseModel
        and value.__module__ == requests.__name__
    )


def _definitions(models: Iterable[type[BaseModel]], mode: Mode) -> dict[str, Any]:
    _, schema = models_json_schema(
        [(model, mode) for model in models], ref_template="#/$defs/{model}"
    )
    definitions: dict[str, Any] = schema.get("$defs", {})
    return definitions


def _literal(value: object) -> str:
    return json.dumps(value)


def ts_type(schema: Mapping[str, Any]) -> str:
    """One JSON-schema node as a TypeScript type expression."""
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[-1]
    if "const" in schema:
        return _literal(schema["const"])
    if "enum" in schema:
        return " | ".join(_literal(item) for item in schema["enum"])
    for key in ("anyOf", "oneOf"):
        if key in schema:
            parts: list[str] = []
            for option in schema[key]:
                text = ts_type(option)
                if text not in parts:
                    parts.append(text)
            return " | ".join(parts)
    kind = schema.get("type")
    if kind == "string":
        return "string"
    if kind in ("integer", "number"):
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "array":
        item = ts_type(schema.get("items", {}))
        return f"({item})[]" if "|" in item else f"{item}[]"
    if kind == "object" or (kind is None and not schema):
        return _object_type(schema)
    raise ValueError(f"unsupported JSON schema node: {dict(schema)!r}")


def _object_type(schema: Mapping[str, Any]) -> str:
    if schema.get("properties"):
        fields = _fields(schema, indent="  ")
        return "{\n" + "\n".join(fields) + "\n}"
    values = schema.get("additionalProperties")
    value = "unknown" if values in (None, True) else ts_type(values)
    names = schema.get("propertyNames")
    key = ts_type(names) if names else "string"
    return f"Record<{key}, {value}>"


def _fields(schema: Mapping[str, Any], *, indent: str) -> list[str]:
    required = set(schema.get("required", []))
    lines: list[str] = []
    for name, field in schema["properties"].items():
        doc = field.get("description")
        if doc:
            lines.extend(_doc(doc, indent))
        optional = "" if name in required else "?"
        lines.append(f"{indent}{name}{optional}: {ts_type(field)};")
    return lines


def _doc(text: str, indent: str) -> list[str]:
    body = [line.rstrip() for line in text.strip().splitlines()]
    if len(body) == 1:
        return [f"{indent}/** {body[0]} */"]
    return [f"{indent}/**", *(f"{indent} * {line}".rstrip() for line in body), f"{indent} */"]


def _declaration(name: str, schema: Mapping[str, Any]) -> str:
    lines = _doc(schema["description"], "") if schema.get("description") else []
    if schema.get("type") == "object" and schema.get("properties"):
        lines.append(f"export interface {name} {{")
        lines.extend(_fields(schema, indent="  "))
        lines.append("}")
    else:
        lines.append(f"export type {name} = {ts_type(schema)};")
    return "\n".join(lines)


def _section(title: str, definitions: Mapping[str, Any], order: Iterable[str]) -> list[str]:
    ordered = [name for name in order if name in definitions]
    ordered += sorted(set(definitions) - set(ordered))
    return [f"// ---- {title} " + "-" * (84 - len(title))] + [
        _declaration(name, definitions[name]) for name in ordered
    ]


def render() -> str:
    reply = _definitions(responses.RESPONSE_MODELS, "serialization")
    asked = _definitions(request_models(), "validation")
    clash = set(reply) & set(asked)
    if clash:
        raise ValueError(f"a model is both a request and a response: {sorted(clash)}")
    blocks = [
        HEADER,
        *_section("responses", reply, (model.__name__ for model in responses.RESPONSE_MODELS)),
        *_section("requests", asked, (model.__name__ for model in request_models())),
    ]
    return "\n\n".join(block.rstrip("\n") for block in blocks) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else "")
    parser.add_argument("--check", action="store_true", help="fail when the file is stale")
    args = parser.parse_args(argv)

    text = render()
    current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
    if args.check:
        if current != text:
            print(
                f"{OUTPUT} is out of date: run `uv run python scripts/gen_api_types.py`",
                file=sys.stderr,
            )
            return 1
        print(f"{OUTPUT.name} is up to date")
        return 0
    if current != text:
        OUTPUT.write_text(text, encoding="utf-8")
        print(f"wrote {OUTPUT}")
    else:
        print(f"{OUTPUT.name} unchanged")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
